// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56D6UE61KB6R-PjP1sAhCVmbbP0K8YaY',
    appId: '1:449689708862:web:7ce83be2bd3f06e525e46f',
    messagingSenderId: '449689708862',
    projectId: 'createfirebase-2e44e',
    authDomain: 'createfirebase-2e44e.firebaseapp.com',
    databaseURL: 'https://createfirebase-2e44e-default-rtdb.firebaseio.com',
    storageBucket: 'createfirebase-2e44e.appspot.com',
    measurementId: 'G-81Q2ZHZSFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AkOTkPpju3KEG9JlLdT4MNreQLcAkU0',
    appId: '1:449689708862:android:fd335fd57c06632525e46f',
    messagingSenderId: '449689708862',
    projectId: 'createfirebase-2e44e',
    databaseURL: 'https://createfirebase-2e44e-default-rtdb.firebaseio.com',
    storageBucket: 'createfirebase-2e44e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iKITZkrVDHfZnceJ9oQLg-iltr088MA',
    appId: '1:449689708862:ios:120e0d8993b74d1625e46f',
    messagingSenderId: '449689708862',
    projectId: 'createfirebase-2e44e',
    databaseURL: 'https://createfirebase-2e44e-default-rtdb.firebaseio.com',
    storageBucket: 'createfirebase-2e44e.appspot.com',
    iosBundleId: 'com.example.flutterTestSerise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3iKITZkrVDHfZnceJ9oQLg-iltr088MA',
    appId: '1:449689708862:ios:ac3fa2659109545825e46f',
    messagingSenderId: '449689708862',
    projectId: 'createfirebase-2e44e',
    databaseURL: 'https://createfirebase-2e44e-default-rtdb.firebaseio.com',
    storageBucket: 'createfirebase-2e44e.appspot.com',
    iosBundleId: 'com.example.flutterTestSerise.RunnerTests',
  );
}
